### ISSUE TITLE
Hooke's Law master checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/hookes-law#1]
## Design
- [x] **Design doc created** (Date: 03/05/2015) 
- [x] **Learning goals and standards identified** (Date: 04/09/2015)
- [x] **Design concept complete**  (Date: 04/09/2015 )
- [x] **Wireframes complete** (Date: 05/14/2015 ) 
- [x] **Mockups complete** (Date: 06/10/2015 ) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Interviews complete** (Date: 06/25/2015) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 09/02/2015) 
  - [x] Performance acceptable
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide
  - [x] Activities and gooru spreadsheet
  - [x] Sim primer (Being tracked in #44)
  - [x] Verify credits
## Implementation
- [x] **Sim repo created** (Date: 04/03/2015) 
  - [x] Collaborators added (such as QA team, designers, etc) 
  - [x] Sim added to active repos list in chipper
  - [x] Sim suggestions doc reviewed
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo
- [x] **Initial development started** (Date: 04/03/2015)
- [x] **Sim feature complete** (Date: 06/25/2015) 
- [x] **Code review complete** (Date: 07/08/2015) 
  - [x] Code review checklist
  - [x] Model description 
- [x] **Published** (Date: 10/21/2015) 
  - [x] Update repo README to published template
## QA
- [x] **Dev testing complete** (Date: 9/9/15 ) 
- [x] **First release candidate** (Date: 10/1/15) 
  - [x] Test matrix deemed complete

**Comment by pixelzoom** [comment]
This sim was published 2 months ago. @ariel-phet Anything in the above check list that needs to be done? If so, recommended to create (and assign) issues for those things, then close this.

**Comment by ariel-phet** [comment]
@arouinfar it looks like the April 29th interview in the design doc did not get full notes pasted in, can you take care of that?

**Comment by ariel-phet** [comment]
@arouinfar ping on this?

**Comment by pixelzoom** [comment]
@arouinfar can we get this issue completed and closed?
